# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IfVE-yXzJzoMnVYoOx8KeH9mdvDuKyrP
"""

"""girilen cümlenin karakterlerini saydırma"""
from typing import Counter
sentence=input("Enter a sentence:")
dict1=dict()
for i in set(sentence):
  dict1[i]=sentence.count(i)
print(dict1)