# -*- coding: utf-8 -*-
"""front_back_char.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19CB7Fxr0Zyis7iEdDovQqQFYDUNPIhxx
"""

def front_back(word):
  if len(word)>1:
    list1=list(word)
    list1.insert(0,list1.pop(-1))
    list1.append(list1.pop(1))
    list1="".join(list1)
    return list1
  else:
    return word