# -*- coding: utf-8 -*-
"""armstrong_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwBOSfZw8dXxXixjZitRTHyBaVVDHCYK
"""

number = input("please enter a positive and integer number: ")
arms = 0
if number.isnumeric():
    for i in number:
    
        arms += int(i) ** len(number)
    if arms == int(number):
        print(f"{number} , is a '{len(number)}' digit number")
        print(arms)
        print(f"{number} is an Armstrong number.")
    else:
        print(f"{number} , is a '{len(number)}' digit number")
        print(arms)
        print(f"{number} is not an Armstrong number")
else:
    print(f"{number} It is an invalid entry. Don't use non-numeric, float, or negative values!")