# -*- coding: utf-8 -*-
"""Covid-19_Risk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwBOSfZw8dXxXixjZitRTHyBaVVDHCYK
"""

while True:
  age=(input("Are you a cigarette addict older than 75 years old? yes or no:"))
  age=age.title()
  if age=="Yes" or age=="No":
     break
  else:
    print("please try again")
while True:
  choronic=(input("Do you have a severe chronic disease? yes or no:"))
  choronic=choronic.title()
  if choronic=="Yes" or choronic=="No":
    break
  else:
    print("please try again")
while True:
    immune=(input("Is your immune system too weak?"))
    immune=immune.title()
    if immune=="Yes" or immune=="No":
      break
    else:
      print("please try again")
risk=(age=="Yes" or choronic=="Yes" or immune=="Yes")
if risk==True :
  print("You are in risky group")
else:
  print("You are not in risky group")