# -*- coding: utf-8 -*-
"""Password Reminder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPZ95xWuM6urvirD5cIT5GITX6QDmoIN
"""

şifre=123456
ad=str(input("adınızı giriniz:"))
kullanıcı_adı="Tuğba"
ad=ad.split(" ")
if ad[0].title()==kullanıcı_adı:
  print("Merhaba {}! şifre:{}".format(ad[0].title(),şifre))
else:
  print("merhaba!{}.Sonra görüşürüz".format(ad[0].capitalize()))