# -*- coding: utf-8 -*-
"""withoutmax_max_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNNrOwtCL2Y4XYZqj_b2QA820ICLvZhT
"""

'''Write a python code that finds the largest number among the 5 numbers
 given by the user as input. It is forbidden to use max() function.'''

list_num=[]
for i in range(1,6):
  num=int(input(f"Please enter {i}th number :"))
  list_num.append(num)
max_num=int()
for i in list_num:
  if i > max_num:
    max_num=i
print(f"max_num is {max_num}")

