# -*- coding: utf-8 -*-
"""FizzBuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBLplgUlXVxFqPtSTfEHeZ77Gbx2XKxq
"""

#fizzbuzz
for i in range(1,100):
  if i%3==0 and i%5==0:
     i ="fizzbuzz"
  elif i%5==0 and i%3!=0:
     i ="buzz"
  elif i%3==0 and i%5!=0:
     i ="fizz"
  print(i)